### ISSUE TITLE
View Navigation Drawer

### ISSUE THREAD

**Issue by tesyant** [tesyant/HouseholdManager#2]
- [ ] adding icons

- [ ] activity_nav_drawer_drawer

- [ ] drawable -> side_nav_bar

**Comment by DiniatiRuaika07** [comment]
tes maksud dari adding icon hanya di drawable ?

**Comment by DiniatiRuaika07** [comment]
I'm Done

**Comment by DiniatiRuaika07** [comment]
next, what can I do
